server:
  port: 9100
spring:
  application:
    name: feed
  datasource:
    url: jdbc:postgresql://localhost:49153/feed
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

